### ISSUE TITLE
subset iucn_habitats to just forest

### ISSUE THREAD

**Issue by hazeljanderson** [bioXgeo/neotropical_plants#4]
[L0_TropicalAndes_IUCNhabitatClassification.Rmd](https://github.com/bioXgeo/neotropical_plants/blob/master/code/L0/L0_TropicalAndes_IUCNhabitatClassification.Rmd)

line 59-66
```
#rename for masking
TA_iucn_habitats_mask <- TA_iucn_habitats
TA_iucn_habitats_mask[TA_iucn_habitats$iucn_habitatclassification_composite_lvl2_ver004 != 106 | TA_iucn_habitats$iucn_habitatclassification_composite_lvl2_ver004 != 109] <- NA
TA_iucn_habitats_forest <- mask(TA_iucn_habitats, TA_iucn_habitats_mask)

plot(TA_iucn_habitats_forest)
```
TA_iucn_habitats_mask is a RasterLayer
class      : RasterLayer 
dimensions : 39325, 38025, 1495333125  (nrow, ncol, ncell)
resolution : 0.0008983153, 0.0008983153  (x, y)
extent     : -91.65421, -57.49577, -22.89177, 12.43448  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs 
source     : r_tmp_2023-07-30_145747.375537_4764_74082.grd 
names      : iucn_habitatclassification_composite_lvl2_ver004 
values     : 100, 1405  (min, max)

Trying to assign all cells with values other than 106 or 109 to NAs to create a raster of just forested cells...
any help would be appreciated

**Comment by bgerstner90** [comment]
Hey Hazel,

If you download the lvl2_frac_1km_ver004.zip you can get individual files for each habitat type-- that way you don't have to subset other habitats out.

Best,
Beth

Beth Gerstner
Ph.D. Candidate | NASA FINESST Fellow
Michigan State University
Department of Fisheries & Wildlife
https://bethgerstner.weebly.com/
www.communityecologylab.com/
________________________________
From: Hazel J. Anderson ***@***.***>
Sent: Sunday, July 30, 2023 3:44:59 PM
To: bioXgeo/neotropical_plants ***@***.***>
Cc: bgerstner90 ***@***.***>; Assign ***@***.***>
Subject: [bioXgeo/neotropical_plants] subset iucn_habitats to just forest (Issue #4)


L0_TropicalAndes_IUCNhabitatClassification.Rmd<https://urldefense.com/v3/__https://github.com/bioXgeo/neotropical_plants/blob/master/code/L0/L0_TropicalAndes_IUCNhabitatClassification.Rmd__;!!HXCxUKc!z9YKeFAc_58SAApdo_1gZnqGqwdjTxk9lyNucpEmik8zwbjltamMZd3rE0rvyPAaklVFBCoBK0H25v29YC0ZxnOUmg$>

line 59-66

#rename for masking
TA_iucn_habitats_mask <- TA_iucn_habitats
TA_iucn_habitats_mask[TA_iucn_habitats$iucn_habitatclassification_composite_lvl2_ver004 != 106 | TA_iucn_habitats$iucn_habitatclassification_composite_lvl2_ver004 != 109] <- NA
TA_iucn_habitats_forest <- mask(TA_iucn_habitats, TA_iucn_habitats_mask)

plot(TA_iucn_habitats_forest)


TA_iucn_habitats_mask is a RasterLayer
class : RasterLayer
dimensions : 39325, 38025, 1495333125 (nrow, ncol, ncell)
resolution : 0.0008983153, 0.0008983153 (x, y)
extent : -91.65421, -57.49577, -22.89177, 12.43448 (xmin, xmax, ymin, ymax)
crs : +proj=longlat +datum=WGS84 +no_defs
source : r_tmp_2023-07-30_145747.375537_4764_74082.grd
names : iucn_habitatclassification_composite_lvl2_ver004
values : 100, 1405 (min, max)

Trying to assign all cells with values other than 106 or 109 to NAs to create a raster of just forested cells...
any help would be appreciated

**Comment by hazeljanderson** [comment]
Yes, that would be easier.
Thank you
